#!/bin/bash
echo "yuvasai hi bro how r u pandu i am fine"
echo "pandu what r u doing bro yuvasai notting bro"
echo "yuvasai what about you bro pandu i am learnig devops bro"
echo "yuvasai oh ok see u tomarrow pandu ok catch up tomarrow"