#!/bin/bash
 
USERID=$(id -u)

if [ $USERID -ne 0 ]
then
    echo "please run the script with root privelages"
    exit 1
fi
dnf list installed git
if [ $? -ne 0 ]
then 
     echo "git is not installed .going to instal it"
     dnf instal git -y
    if [ $? -ne 0 ]
    then 
        echo "git instaletion is failed"
        exit 1
    else
        echo "git is installed sucess"
    fi
else 
    echo "git installed already .nothing to do"
fi

dnf list installed  mysql
if [ $? -ne 0 ]
then
    echo "mysql is not installled ging to instal it"
    dnf install mysql -y
    if [ $? -ne 0 ]
    then 
        echo "mysql installation is filed . check it"
        exit 1
    else
        echo "mysql instalation sucess"
    fi
else
    echo "mysql is installed already .nothing to do"
fi                             
    